### PR TITLE
Fixed file-link-multiple.

### PR DESCRIPTION
**Pull request by oimken**
`$$zoneVar` shows nothing.

### CODE REVIEW

**Comment by nWidart** [comment]
This is a breaking change. Let's hold of on this for a major version.

**Comment by oimken** [comment]
Ok, I don't know when and why it is not working... 
 I just copy it out to my module view and make it works for now. :)

**Comment by nWidart** [comment]
You need to append `Files` to your variable in your controller currently.

**Comment by oimken** [comment]
I known what's wrong....
In https://www.youtube.com/watch?v=QcxmPDfq5Pg,  at 00:13:16, you use the variable `$gallery`, 
But in doc, should add `Files`

**Comment by nWidart** [comment]
Yep, I actually fix it later in the video, not sure I show it though.

**Comment by oimken** [comment]
I am very very sorry, I miss that moment..........

**Comment by nWidart** [comment]
No worries. I'm not sure why I added that suffix. Something to change in 2.0 maybe.

**Pull request closed without merging**
