### PR TITLE
Added optional simple choose for adding only original image in media-grid

### PR DESCRIPTION
**Pull request by ruscon**
Add tag pls, if all is ok

### CODE REVIEW

**Comment by ruscon** [comment]
> code-review/gitcolony — 0/0 qa 0/0 dev, 0 issues, Linked PRs not ok
 @nWidart, what happens with it ?

**Comment by nWidart** [comment]
you can ignore gitcolony.

**Comment by nWidart** [comment]
hello,

this is showing a huge diff, hard to see what was actually changed.

**Comment by ruscon** [comment]
Primary idea described in Config/config.php changes

**Comment by nWidart** [comment]
yes, that would be the easy part to understand since no big diff.

Could you update your PR with the current upstream ?

**Comment by nWidart** [comment]
Also, don't move big chunks of code for the sake of it, this is what caused the big diff. Unless required, use the same position.

**Comment by ruscon** [comment]
> Could you update your PR with the current upstream ?
Ok, I'll do today or tomorrow

**Comment by nWidart** [comment]
Thank you for the contribution, however I'm going to need to close this as I've opted for another solution for the problem.

Indeed now the dropdown is only displayed if accessed via the wysiwyg, otherwise it will always be the simple 'import this' button.

**Comment by ruscon** [comment]
cool, thx

**Pull request closed without merging**
