### PR TITLE
Make styling consistent #2

### PR DESCRIPTION
**Pull request by armababy**
Update edit views also same as [pull#45](https://github.com/AsgardCms/Media/pull/45)

### CODE REVIEW

**Comment by nWidart** [comment]
Thanks 👍

**Comment by nWidart** [comment]
I fixed a missing `"` and tagged [1.25.6](https://github.com/AsgardCms/Media/releases/tag/1.25.6) 😄

**Comment by armababy** [comment]
Thanks :D then it was missing in both new and old.

**Comment by nWidart** [comment]
Oh damn ok, fixed it on the new as well.

**Pull request merged**
